<!DOCTYPE html>
<html>
<head>
	<title>FAQs</title>
	<link rel="shortcut icon" href="http://www.revs.org.uk/wp-content/uploads/2013/04/favicon-3.png" />
    <link rel="stylesheet" href="http://www.revs.org.uk/wp-content/themes/Harmony/style.css?ver=3.5.1" type="text/css" />
    <link rel="stylesheet" href="http://www.revs.org.uk/?custom-css=1&amp;csblog=1&amp;cscache=6&amp;csrev=119" type="text/css" />
    <link rel='stylesheet' id='harmony-fonts-css'  href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,700italic,800italic,400,300,700,800&#038;subset=latin,latin-ext' type='text/css' media='all' />
    <link rel="stylesheet" href="/style.css" type="text/css" />
</head>
<body>
	<div id='navbar'>
		<a href="/"><img src='/logo.png' id='logo' /></a>
	{{>nav}}
	</div>
	<div class='container'>
	<h1 class='title'>{{title}}</h1>
{{{content}}}
</div>
</body>
</html>